### ISSUE TITLE
Attack Damage

### ISSUE THREAD

**Issue by HacoKavanah** [cschierig/Rudimentary#1]
My game has the flint hatchet attack damage at 11, is this correct? Or has it been modified by another mod? If it truly is that powerful, could there be a value in the config to change the attack power of the hatchet? (and the pickaxe as well).

**Comment by cschierig** [comment]
It's supposed to be 9 (as much as a stone axe), I must have forgotten to change it. I'll fix this in the next release.

**Comment by HacoKavanah** [comment]
Thanks! and I'm pretty sure flint pickaxe had like 7 attack damage as well?

**Comment by cschierig** [comment]
I've fixed both. The release should come out later today alongside an early game furnace.

**Comment by cschierig** [comment]
Fixed with [0.2.0](https://modrinth.com/mod/rudimentary/version/0.2.0)
